COPY docker-entrypoint.sh /entrypoint.sh

# ------------------------------------------------------------------------------
# Redefine commands.
# ------------------------------------------------------------------------------
ENTRYPOINT [ "/entrypoint.sh" ]
CMD ["pydio"]
